package core;


/**
* core/WANCorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WANCorba.idl
* 8 Ноябрь 2007 г. 21:54:08 MSK
*/

public abstract class WANCorbaPOA extends org.omg.PortableServer.Servant
 implements core.WANCorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    WANCorbaPOA._methods.put ("receivePacket", new java.lang.Integer (0));
    WANCorbaPOA._methods.put ("setServiceName", new java.lang.Integer (1));
    WANCorbaPOA._methods.put ("shutdown", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)WANCorbaPOA._methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // core/WANCorba/receivePacket
       {
         String inPacket = in.read_string ();
         this.receivePacket (inPacket);
         out = $rh.createReply();
         break;
       }

       case 1:  // core/WANCorba/setServiceName
       {
         String inService = in.read_string ();
         this.setServiceName (inService);
         out = $rh.createReply();
         break;
       }

       case 2:  // core/WANCorba/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:core/WANCorba:1.0"};

  @Override
public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return WANCorbaPOA.__ids.clone ();
  }

  public WANCorba _this() 
  {
    return WANCorbaHelper.narrow(
    super._this_object());
  }

  public WANCorba _this(org.omg.CORBA.ORB orb) 
  {
    return WANCorbaHelper.narrow(
    super._this_object(orb));
  }


} // class WANCorbaPOA
