package core;

/**
* core/WANCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WANCorba.idl
* 8 Ноябрь 2007 г. 21:54:08 MSK
*/

public final class WANCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public core.WANCorba value = null;

  public WANCorbaHolder ()
  {
  }

  public WANCorbaHolder (core.WANCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = core.WANCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    core.WANCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return core.WANCorbaHelper.type ();
  }

}
