package core;


/**
* core/WANCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WANCorba.idl
* 8 Ноябрь 2007 г. 21:54:08 MSK
*/

public interface WANCorba extends WANCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WANCorba
