package core;


/**
* core/WANCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WANCorba.idl
* 8 Ноябрь 2007 г. 21:54:08 MSK
*/

abstract public class WANCorbaHelper
{
  private static String  _id = "IDL:core/WANCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, core.WANCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (WANCorbaHelper.type ());
    WANCorbaHelper.write (out, that);
    a.read_value (out.create_input_stream (), WANCorbaHelper.type ());
  }

  public static core.WANCorba extract (org.omg.CORBA.Any a)
  {
    return WANCorbaHelper.read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (WANCorbaHelper.__typeCode == null)
    {
      WANCorbaHelper.__typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (core.WANCorbaHelper.id (), "WANCorba");
    }
    return WANCorbaHelper.__typeCode;
  }

  public static String id ()
  {
    return WANCorbaHelper._id;
  }

  public static core.WANCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return WANCorbaHelper.narrow (istream.read_Object (_WANCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, core.WANCorba value)
  {
    ostream.write_Object (value);
  }

  public static core.WANCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof core.WANCorba)
      return (core.WANCorba)obj;
    else if (!obj._is_a (WANCorbaHelper.id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      core._WANCorbaStub stub = new core._WANCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static core.WANCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof core.WANCorba)
      return (core.WANCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      core._WANCorbaStub stub = new core._WANCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
